---
title: "Research"
---

## Publications

**Loffredo, Joseph R.** and Suyeol Yun. 2025. "[Agent-Enhanced Large Language Models for Researching Political Institutions](http://dx.doi.org/10.1561/113.00000125)." *Journal of Political Institutions and Political Economy* 6 (3-4). 277-300. `DOI: 10.1561/113.00000125`. Paper preprint is available [here](https://doi.org/10.48550/arXiv.2503.13524).

<details>
<summary>Abstract</summary>
The applications of Large Language Models (LLMs) in political science are rapidly expanding. This paper demonstrates how LLMs, when augmented with predefined functions and specialized tools, can serve as dynamic agents capable of streamlining tasks such as data collection, preprocessing, and analysis. Central to this approach is Agentic RAG, which equips LLMs with action-calling capabilities for interaction with external knowledge bases. Beyond information retrieval, LLM agents incorporate modular tools for tasks like document summarization, transcript coding, qualitative variable classification, and statistical modeling, enabling adaptability across diverse research contexts. To demonstrate the potential of this approach, we introduce CongressRA, an LLM agent designed to support scholars studying the U.S. Congress. Through this example, we highlight how LLM agents can reduce the costs of replicating, testing, and extending empirical research using the domain-specific data that drives the study of political institutions.
</details>

<br>

Kuriwaki, Shiro, Mason Reece, Samuel Baltz, Aleksandra Conevska, **Joseph R. Loffredo**, Can E. Mutlu, Taran Samarth, Kevin E. Acevedo Jetter, Zachary Djanogly Garai, Kate Murray, Shigeo Hirano, Jeffrey B. Lewis, James M. Snyder, Jr., and Charles Stewart, III. 2024. "[Cast vote records: A database of ballots from the 2020 U.S. Election](https://doi.org/10.1038/s41597-024-04017-1)." *Scientific Data* 11 (1304). `DOI: 10.1038/s41597-024-04017-1`. Public dataset is available [here](https://doi.org/10.7910/DVN/PQQ3KV). Paper preprint is available [here](https://arxiv.org/abs/2411.05020).

<details>
<summary>Abstract</summary>
Ballots are the core records of elections. Electronic records of actual ballots cast (cast vote records) are available to the public in some jurisdictions. However, they have been released in a variety of formats and have not been independently evaluated. Here we introduce a database of cast vote records from the 2020 U.S. general election. We downloaded publicly available unstandardized cast vote records, standardized them into a multi-state database, and extensively compared their totals to certified election results. Our release includes vote records for President, Governor, U.S. Senate and House, and state upper and lower chambers, covering 42.7 million voters in 20 states who voted for more than 2,200 candidates. This database serves as a uniquely granular administrative dataset for studying voting behavior and election administration. Using this data, we show that in battleground states, 1.9 percent of solid Republicans (as defined by their congressional and state legislative voting) in our database split their ticket for Joe Biden, while 1.2 percent of solid Democrats split their ticket for Donald Trump.
</details>

<br>

Jaffe, Jacob, **Joseph R. Loffredo**, Samuel Baltz, Alejandro Flores, and Charles Stewart III. 2024. "[Trust in the Count: Improving Voter Confidence with Post-Election Audits](https://doi.org/10.1093/poq/nfae029)." *Public Opinion Quarterly* 88 (SI): 585-607. `DOI: 10.1093/poq/nfae029`. Replication materials are available [here](https://osf.io/xdn89/).

<details>
<summary>Abstract</summary>
Post-election audits are thought to bolster voter confidence in elections, but it is unclear which aspects of audits drive public trust. Using pre-registered vignette and conjoint survey experiments administered by YouGov on a sample of 2,000 American respondents, we find that how an audit is conducted is more important than what an audit finds. Structural features of audits, like who conducts it and how its results are announced, turn out to be more consequential to voter evaluations of election results than the actual discrepancy found. Moreover, while Democrats and Republicans have increasingly divided views of the state of democracy in the United States, they are similarly receptive to information presented about audits, and largely agree that audits are effective tools for detecting errors in vote counting. Our findings thus reinforce the expectation that audits do increase voter trust and suggest that election administrators can strengthen voter confidence by making audits as transparent as possible.
</details>

## Under Review

**Loffredo, Joseph R.**, Michael Hankinson, and Asya Magazinnik. 2025. "Reform Drift: How Incumbent Protection Undermines Descriptive Representation in Local Government." Paper preprint is available [here](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5372605).

<details>
<summary>Abstract</summary>
Institutional reforms designed to enhance democratic representation often place implementation in the hands of incumbents. We examine how incumbents use this control to protect their interests by leveraging the California Voting Rights Act of 2001, which prompted hundreds of jurisdictions to switch from at-large to district elections to improve minority representation. Using a state-of-the-art redistricting simulation algorithm, we show that adopted council maps overwhelmingly placed incumbents alone in their districts-63% of cities' plans ranked in the 99th percentile or higher for avoidance of incumbent pairings. This pattern was especially pronounced in smaller, whiter cities with lower turnout and more competitive elections. Crucially, incumbent protection deters challenger entry and reduces Latino electoral success. In Latino-opportunity districts, a lone incumbent decreases the probability of a Latino being elected by 19 percentage points. Our findings show how reforms can be blunted by those empowered to implement them, ultimately reinforcing existing power structures.
</details>

<br>

**Loffredo, Joseph R.**, Jillian Andres Rothschild, and Alejandro Flores. 2025. "America Decides, Networks Project: How Voters Respond to Election Night Coverage." Paper preprint is available [here](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5396574).

<details>
<summary>Abstract</summary>
While election officials count votes and certify winners, media outlets play a critical yet unofficial role in presenting and contextualizing results. Public trust in elections, however, depends on whether outcomes are seen as clear, legitimate, and widely accepted. In a fragmented media environment, partisans increasingly rely on ideologically aligned outlets, raising the question: how can there be clarity and acceptance when the source and timing of projections differ? In this study, we utilize a series of survey vignette experiments fielded before and after the 2024 U.S. election to test this question. Our findings reveal that voter confidence is indeed shaped by projection source and timing, with conflicting projections eroding trust. We complement these experiments with a survey fielded on Election Night to examine the real-time dynamics of voter confidence and emotional affect. We find suggestive evidence that confidence fluctuates throughout Election Night among politically disengaged voters, while supporters of the losing candidate experience rising pessimism as the outcome becomes apparent. These results show that even when citizens receive the same substantive information, the context, perspective, and framing in which it is delivered shapes how it is processed. Thus, our work highlights that variation in the editorial choices of media outlets can deepen divides in how partisans evaluate the performance of elections. This underscores the need for both media and election officials to consider how election coverage influences voter confidence and to take steps that strengthen perceptions of democratic legitimacy.
</details>

## Working Papers

"America Decides, Networks Project: How Voters Respond to Election Night Coverage" (with Jillian Andres Rothschild and Alejandro Flores)

"Where We Vote: The Changing Landscape of Where Americans Cast Votes" (with Alejandro Flores)

"State Confidence in Elections: Results, Practice, and Policy" (with Charles Stewart III)

"Trends in Nationalization of State and Local Elections: Evidence from Precinct Data" (with Shigeo Hirano, Mason Reece, and James M. Snyder, Jr.)

"Lines for Representation: Assessing District Elections as a Remedy in State Voting Rights Acts" (with Michael Hankinson and Asya Magazinnik)
